// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HayCERAlhOri0B41awGRpgs9eNxYDcI',
    appId: '1:50396224898:web:429b19c65fd4e50ac8039b',
    messagingSenderId: '50396224898',
    projectId: 'trackify-b902c',
    authDomain: 'trackify-b902c.firebaseapp.com',
    storageBucket: 'trackify-b902c.firebasestorage.app',
    measurementId: 'G-VQWS4HRKTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5jBkquLK7yevz2eHhZ0CmcmRXiSkhzAU',
    appId: '1:50396224898:android:dc00899e3e87c52bc8039b',
    messagingSenderId: '50396224898',
    projectId: 'trackify-b902c',
    storageBucket: 'trackify-b902c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDylEl-pgUBa_PA1xsoaDBscQwl0uegd4Y',
    appId: '1:50396224898:ios:022f531c9dd9eb73c8039b',
    messagingSenderId: '50396224898',
    projectId: 'trackify-b902c',
    storageBucket: 'trackify-b902c.firebasestorage.app',
    iosBundleId: 'com.example.trackifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDylEl-pgUBa_PA1xsoaDBscQwl0uegd4Y',
    appId: '1:50396224898:ios:022f531c9dd9eb73c8039b',
    messagingSenderId: '50396224898',
    projectId: 'trackify-b902c',
    storageBucket: 'trackify-b902c.firebasestorage.app',
    iosBundleId: 'com.example.trackifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5HayCERAlhOri0B41awGRpgs9eNxYDcI',
    appId: '1:50396224898:web:8baf9a8f58f2cc14c8039b',
    messagingSenderId: '50396224898',
    projectId: 'trackify-b902c',
    authDomain: 'trackify-b902c.firebaseapp.com',
    storageBucket: 'trackify-b902c.firebasestorage.app',
    measurementId: 'G-7D8VGJPBDJ',
  );
}
